# .github/workflows/nodejs.yml
#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
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [10]
        os: [redhat]

    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        # key: ${{ secrets.KEY }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/myutubclone-backend
          git pull origin master
          npm install --production
          npm run stop
          npm run start
